config:
  actors:
    player:
      width: 100
      height: 50
      color: [0, 255, 0]
      image: ""
      sfx:
        hit: "assets/sfx/sfx_hit.wav"
#        death: "assets/sfx/sfx_death.wav"
        death: "assets/sfx/sfx_hit.wav"
    invaders:
      basic:
        width: 50
        height: 50
        color: [255, 0, 255]
        images:
          healthy: "assets/img/invader_1.png"
          damaged: "assets/img/invader_2.png"
          dying: "assets/img/invader_3.png"
        sfx:
          hit: "assets/sfx/sfx_hit.wav"
    projectiles:
      basic:
        width: 5
        height: 10
        color: [255, 0, 0]
        image: "assets/img/projectile_1.png"
        sfx:
          hit: "assets/sfx/sfx_hit.wav"
